### ISSUE TITLE
Errors and warnings during flashing

### ISSUE THREAD

**Issue by reynas** [joelsernamoreno/EvilCrow-Keylogger#10]
Host: Ubuntu 20.04.1
After flashing, it still shows version v1.2 with buttons view log/delete log (livepayload is missing)
Do you have any guidance here? Thanks!

Fulll log:

root@user-HP:~/keylogger-pio# ./flash.sh 
Processing LilyPadUSB (platform: atmelavr; framework: arduino; board: LilyPadUSB)
-----------------------------------------------------------------------------------------------------------------------------------------
Platform Manager: Installing atmelavr
Platform Manager: atmelavr @ 3.0.0 has been installed!
The platform 'atmelavr' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing platformio/toolchain-atmelavr @ ~1.50400.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-atmelavr @ 1.50400.190710 has been installed!
Tool Manager: Installing platformio/framework-arduino-avr @ ~5.1.0
Downloading  [####################################]  100%
Tool Manager: framework-arduino-avr @ 5.1.0 has been installed!
Tool Manager: Installing platformio/tool-avrdude @ ~1.60300.0
Tool Manager: tool-avrdude @ 1.60300.200527 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40001.0
Tool Manager: tool-scons @ 4.40001.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/LilyPadUSB.html
PLATFORM: Atmel AVR (3.0.0) > Arduino LilyPad USB
HARDWARE: ATMEGA32U4 8MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES: 
 - framework-arduino-avr 5.1.0 
 - tool-avrdude 1.60300.200527 (6.3.0) 
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
Converting programmer.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 5 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/LilyPadUSB/src/programmer.ino.cpp.o
Archiving .pio/build/LilyPadUSB/libFrameworkArduinoVariant.a
Indexing .pio/build/LilyPadUSB/libFrameworkArduinoVariant.a
Compiling .pio/build/LilyPadUSB/FrameworkArduino/CDC.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial0.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial1.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial2.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial3.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/PluggableUSB.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Print.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Stream.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Tone.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/USBCore.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WInterrupts.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WMath.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WString.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/abi.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/hooks.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/main.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/new.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_analog.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_digital.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_pulse.S.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_pulse.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_shift.c.o
Archiving .pio/build/LilyPadUSB/libFrameworkArduino.a
Indexing .pio/build/LilyPadUSB/libFrameworkArduino.a
Linking .pio/build/LilyPadUSB/firmware.elf
Checking size .pio/build/LilyPadUSB/firmware.elf
Building .pio/build/LilyPadUSB/firmware.hex
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  21.2% (used 542 bytes from 2560 bytes)
Flash: [==        ]  16.2% (used 4648 bytes from 28672 bytes)
Configuring upload protocol...
AVAILABLE: avr109
CURRENT: upload_protocol = avr109
Looking for upload port...

Warning! Please install `99-platformio-udev.rules`. 
More details: https://docs.platformio.org/page/faq.html#platformio-udev-rules

Auto-detected: /dev/ttyACM0
Forcing reset using 1200bps open/close on port /dev/ttyACM0
Waiting for the new upload port...
Uploading .pio/build/LilyPadUSB/firmware.hex

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: reading input file ".pio/build/LilyPadUSB/firmware.hex"
avrdude: writing flash (4648 bytes):

Writing | ################################################## | 100% 0.39s

avrdude: 4648 bytes of flash written
avrdude: verifying flash memory against .pio/build/LilyPadUSB/firmware.hex:
avrdude: load data flash data from input file .pio/build/LilyPadUSB/firmware.hex:
avrdude: input file .pio/build/LilyPadUSB/firmware.hex contains 4648 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.06s

avrdude: verifying ...
avrdude: 4648 bytes of flash verified

avrdude: safemode: Fuses OK (E:CE, H:D8, L:FF)

avrdude done.  Thank you.

===================================================================== [SUCCESS] Took 38.39 seconds =====================================================================
Processing keylogger (platform: espressif32@1.10.0; framework: arduino; board: pico32)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Platform Manager: Installing espressif32 @ 1.10.0
Platform Manager: espressif32 @ 1.10.0 has been installed!
The platform 'espressif32@1.10.0' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing toolchain-xtensa32 @ ~2.50200.0
Tool Manager: Warning! More than one package has been found by toolchain-xtensa32 @ ~2.50200.0 requirements:
 - platformio/toolchain-xtensa32 @ 2.80200.200827
 - tasmota/toolchain-xtensa32 @ 2.80400.2020
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-xtensa32 @ 2.50200.80 has been installed!
Tool Manager: Installing framework-arduinoespressif32 @ ~2.10003.190916
Tool Manager: Warning! More than one package has been found by framework-arduinoespressif32 @ ~2.10003.190916 requirements:
 - platformio/framework-arduinoespressif32 @ 3.10004.201016
 - tasmota/framework-arduinoespressif32 @ 3.10004.1
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoespressif32 @ 2.10003.190916 has been installed!
Tool Manager: Installing git+https://github.com/AprilBrother/esptool.git#keylogger
git version 2.25.1
Cloning into '/root/.platformio/.cache/tmp/pkg-installing-el67pepj'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 147 (delta 11), reused 104 (delta 7), pack-reused 0
Receiving objects: 100% (147/147), 5.24 MiB | 5.63 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Error: Could not find one of 'package.json' manifest files in the package
Processing LilyPadUSB (platform: atmelavr; framework: arduino; board: LilyPadUSB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/LilyPadUSB.html
PLATFORM: Atmel AVR (3.0.0) > Arduino LilyPad USB
HARDWARE: ATMEGA32U4 8MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES: 
 - framework-arduino-avr 5.1.0 
 - tool-avrdude 1.60300.200527 (6.3.0) 
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
Converting ATMEGA32U4.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing id:890
Library Manager: Mouse @ 1.0.1 has been installed!
Library Manager: Installing id:868
Library Manager: SD @ 1.2.4 has been installed!
Found 9 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Mouse> 1.0.1
|   |-- <HID> 1.0
|-- <SD> 1.2.4
|   |-- <SPI> 1.0
|-- <Keyboard> 1.0.1
|   |-- <HID> 1.0
|-- <SPI> 1.0
|-- <USB-Host-Shield-20> 1.3.2
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio/build/LilyPadUSB/src/ATMEGA32U4.ino.cpp.o
Compiling .pio/build/LilyPadUSB/lib17e/HID/HID.cpp.o
Archiving .pio/build/LilyPadUSB/lib17e/libHID.a
Indexing .pio/build/LilyPadUSB/lib17e/libHID.a
/root/EvilCrow-Keylogger/code/ATMEGA32U4/ATMEGA32U4.ino: In member function 'virtual void KbdRptParser::OnKeyUp(uint8_t, uint8_t)':
/root/EvilCrow-Keylogger/code/ATMEGA32U4/ATMEGA32U4.ino:70:38: warning: right operand of comma operator has no effect [-Wunused-value]
   key_modifier = key|modifiersard,HEX;
                                      ^
/root/EvilCrow-Keylogger/code/ATMEGA32U4/ATMEGA32U4.ino: In function 'char ProcessCommand()':
/root/EvilCrow-Keylogger/code/ATMEGA32U4/ATMEGA32U4.ino:130:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
Compiling .pio/build/LilyPadUSB/lib5df/Mouse/Mouse.cpp.o
Archiving .pio/build/LilyPadUSB/lib5df/libMouse.a
Indexing .pio/build/LilyPadUSB/lib5df/libMouse.a
Compiling .pio/build/LilyPadUSB/lib05b/SPI/SPI.cpp.o
Compiling .pio/build/LilyPadUSB/lib206/SD/File.cpp.o
Archiving .pio/build/LilyPadUSB/lib05b/libSPI.a
Indexing .pio/build/LilyPadUSB/lib05b/libSPI.a
Compiling .pio/build/LilyPadUSB/lib206/SD/SD.cpp.o
Compiling .pio/build/LilyPadUSB/lib206/SD/utility/Sd2Card.cpp.o
Compiling .pio/build/LilyPadUSB/lib206/SD/utility/SdFile.cpp.o
Compiling .pio/build/LilyPadUSB/lib206/SD/utility/SdVolume.cpp.o
Compiling .pio/build/LilyPadUSB/lib395/Keyboard/Keyboard.cpp.o
Archiving .pio/build/LilyPadUSB/lib206/libSD.a
Indexing .pio/build/LilyPadUSB/lib206/libSD.a
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/BTD.cpp.o
Archiving .pio/build/LilyPadUSB/lib395/libKeyboard.a
Indexing .pio/build/LilyPadUSB/lib395/libKeyboard.a
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/BTHID.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/PS3BT.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/PS3USB.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/PS4Parser.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/PSBuzz.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/SPP.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/Usb.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/Wii.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/XBOXOLD.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/XBOXONE.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/XBOXRECV.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/XBOXUSB.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/adk.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/cdc_XR21B1411.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/cdcacm.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/cdcftdi.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/cdcprolific.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/hidboot.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/hidcomposite.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/hidescriptorparser.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/hiduniversal.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/hidusagetitlearrays.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/masstorage.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/max_LCD.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/message.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/parsetools.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/usbh_midi.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/usbhid.cpp.o
Compiling .pio/build/LilyPadUSB/lib404/USB_Host_Shield_2.0/usbhub.cpp.o
Archiving .pio/build/LilyPadUSB/libFrameworkArduinoVariant.a
Indexing .pio/build/LilyPadUSB/libFrameworkArduinoVariant.a
Compiling .pio/build/LilyPadUSB/FrameworkArduino/CDC.cpp.o
Archiving .pio/build/LilyPadUSB/lib404/libUSB_Host_Shield_2.0.a
Indexing .pio/build/LilyPadUSB/lib404/libUSB_Host_Shield_2.0.a
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial0.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial1.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial2.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/HardwareSerial3.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/PluggableUSB.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Print.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Stream.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/Tone.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/USBCore.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WInterrupts.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WMath.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/WString.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/abi.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/hooks.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/main.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/new.cpp.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_analog.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_digital.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_pulse.S.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_pulse.c.o
Compiling .pio/build/LilyPadUSB/FrameworkArduino/wiring_shift.c.o
Archiving .pio/build/LilyPadUSB/libFrameworkArduino.a
Indexing .pio/build/LilyPadUSB/libFrameworkArduino.a
Linking .pio/build/LilyPadUSB/firmware.elf
Building .pio/build/LilyPadUSB/firmware.hex
Checking size .pio/build/LilyPadUSB/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=======   ]  67.2% (used 1721 bytes from 2560 bytes)
Flash: [==========]  99.8% (used 28616 bytes from 28672 bytes)
Configuring upload protocol...
AVAILABLE: avr109
CURRENT: upload_protocol = avr109

Warning! Please install `99-platformio-udev.rules`. 
More details: https://docs.platformio.org/page/faq.html#platformio-udev-rules

Looking for upload port...
Auto-detected: /dev/ttyACM0
Forcing reset using 1200bps open/close on port /dev/ttyACM0
Waiting for the new upload port...
Uploading .pio/build/LilyPadUSB/firmware.hex

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: reading input file ".pio/build/LilyPadUSB/firmware.hex"
avrdude: writing flash (28616 bytes):

Writing | ################################################## | 100% 2.27s

avrdude: 28616 bytes of flash written
avrdude: verifying flash memory against .pio/build/LilyPadUSB/firmware.hex:
avrdude: load data flash data from input file .pio/build/LilyPadUSB/firmware.hex:
avrdude: input file .pio/build/LilyPadUSB/firmware.hex contains 28616 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.33s

avrdude: verifying ...
avrdude: 28616 bytes of flash verified

avrdude: safemode: Fuses OK (E:CE, H:D8, L:FF)

avrdude done.  Thank you.

===================================================================== [SUCCESS] Took 19.73 seconds =====================================================================

**Comment by reynas** [comment]
Resolution for https://github.com/joelsernamoreno/EvilCrow-Keylogger/issues/9 helped as well.

**Comment by joelsernamoreno** [comment]
Hello!
Have you solved this or do you need help?

**Comment by reynas** [comment]
Hi
I solved this with the help of your comments on the issue #9 
Everything works smoothly now, thanks a lot!
