### ISSUE TITLE
Errors during Flash

### ISSUE THREAD

**Issue by auyx** [joelsernamoreno/EvilCrow-Keylogger#12]
Hi I'm getting the following during the flashing process and I cant figure out what the problem is. Hoping you could help. 

auyx@auyx-HP-635-Notebook-PC:~/keylogger-pio$ ./flash.sh
Processing LilyPadUSB (platform: atmelavr; framework: arduino; board: LilyPadUSB)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/LilyPadUSB.html
PLATFORM: Atmel AVR (3.2.0) > Arduino LilyPad USB
HARDWARE: ATMEGA32U4 8MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES: 
 - framework-arduino-avr 5.1.0 
 - tool-avrdude 1.60300.200527 (6.3.0) 
 - toolchain-atmelavr 1.70300.191015 (7.3.0)
Converting programmer.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 5 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/LilyPadUSB/src/programmer.ino.cpp.o
Linking .pio/build/LilyPadUSB/firmware.elf
Checking size .pio/build/LilyPadUSB/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  21.2% (used 542 bytes from 2560 bytes)
Flash: [==        ]  16.0% (used 4580 bytes from 28672 bytes)
Configuring upload protocol...
AVAILABLE: avr109
CURRENT: upload_protocol = avr109
Looking for upload port...
Auto-detected: /dev/ttyACM0
Forcing reset using 1200bps open/close on port /dev/ttyACM0
Waiting for the new upload port...
Uploading .pio/build/LilyPadUSB/firmware.hex

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: reading input file ".pio/build/LilyPadUSB/firmware.hex"
avrdude: writing flash (4580 bytes):

Writing | ################################################## | 100% 0.44s

avrdude: 4580 bytes of flash written
avrdude: verifying flash memory against .pio/build/LilyPadUSB/firmware.hex:
avrdude: load data flash data from input file .pio/build/LilyPadUSB/firmware.hex:
avrdude: input file .pio/build/LilyPadUSB/firmware.hex contains 4580 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.15s

avrdude: verifying ...
avrdude: 4580 bytes of flash verified

avrdude: safemode: Fuses OK (E:CE, H:D8, L:FF)

avrdude done.  Thank you.

========================= [SUCCESS] Took 6.28 seconds =========================
Processing keylogger (platform: espressif32@1.10.0; framework: arduino; board: pico32)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/pico32.html
PLATFORM: Espressif 32 (1.10.0) > ESP32 Pico Kit
HARDWARE: ESP32 80MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 2.10003.190916 (1.0.3) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - tool-mkspiffs 2.230.0 (2.30) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 26 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Generating partitions .pio/build/keylogger/partitions.bin
Archiving .pio/build/keylogger/libFrameworkArduinoVariant.a
Indexing .pio/build/keylogger/libFrameworkArduinoVariant.a
Compiling .pio/build/keylogger/FrameworkArduino/Esp.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/IPv6Address.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/MD5Builder.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/Print.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/Stream.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/StreamString.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/WMath.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/WString.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/base64.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/cbuf.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-adc.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-bt.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-cpu.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-dac.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-gpio.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-i2c.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-ledc.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-matrix.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-misc.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-psram.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-rmt.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-sigmadelta.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-spi.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-time.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-timer.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-touch.c.o
Compiling .pio/build/keylogger/FrameworkArduino/esp32-hal-uart.c.o
Compiling .pio/build/keylogger/FrameworkArduino/libb64/cdecode.c.o
Compiling .pio/build/keylogger/FrameworkArduino/libb64/cencode.c.o
Compiling .pio/build/keylogger/FrameworkArduino/main.cpp.o
Compiling .pio/build/keylogger/FrameworkArduino/stdlib_noniso.c.o
Compiling .pio/build/keylogger/FrameworkArduino/wiring_pulse.c.o
Compiling .pio/build/keylogger/FrameworkArduino/wiring_shift.c.o
Archiving .pio/build/keylogger/libFrameworkArduino.a
Indexing .pio/build/keylogger/libFrameworkArduino.a
Linking .pio/build/keylogger/firmware.elf
.pio/build/keylogger/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x4): undefined reference to `setup()'
.pio/build/keylogger/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `loop()'
.pio/build/keylogger/libFrameworkArduino.a(main.cpp.o): In function `loopTask(void*)':
/home/auyx/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14: undefined reference to `setup()'
/home/auyx/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:17: undefined reference to `loop()'
collect2: error: ld returned 1 exit status
*** [.pio/build/keylogger/firmware.elf] Error 1
========================= [FAILED] Took 37.93 seconds =========================
Processing LilyPadUSB (platform: atmelavr; framework: arduino; board: LilyPadUSB)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/LilyPadUSB.html
PLATFORM: Atmel AVR (3.2.0) > Arduino LilyPad USB
HARDWARE: ATMEGA32U4 8MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES: 
 - framework-arduino-avr 5.1.0 
 - tool-avrdude 1.60300.200527 (6.3.0) 
 - toolchain-atmelavr 1.70300.191015 (7.3.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 7 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Mouse> 1.0.1
|-- <SD> 1.2.4
Building in release mode
Compiling .pio/build/LilyPadUSB/lib91c/Mouse/Mouse.cpp.o
In file included from .pio/libdeps/LilyPadUSB/Mouse/src/Mouse.cpp:22:0:
.pio/libdeps/LilyPadUSB/Mouse/src/Mouse.h:25:10: fatal error: HID.h: No such file or directory

*************************************************************
* Looking for HID.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:HID.h"
* Web  > https://platformio.org/lib/search?query=header:HID.h
*
*************************************************************

 #include "HID.h"
          ^~~~~~~
compilation terminated.
Compiling .pio/build/LilyPadUSB/libe71/SD/utility/Sd2Card.cpp.o
*** [.pio/build/LilyPadUSB/lib91c/Mouse/Mouse.cpp.o] Error 1
.pio/libdeps/LilyPadUSB/SD/src/utility/Sd2Card.cpp:31:12: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://platformio.org/lib/search?query=header:SPI.h
*
*************************************************************

   #include <SPI.h>
            ^~~~~~~
compilation terminated.
*** [.pio/build/LilyPadUSB/libe71/SD/utility/Sd2Card.cpp.o] Error 1
========================== [FAILED] Took 2.06 seconds ==========================

**Comment by joelsernamoreno** [comment]
Hello!

You have keylogger-pio and EvilCrow-Keylogger in the same directory?

Can you run flash.sh without verbose, export the output to a text file and send it to me?

Thanks

**Comment by joelsernamoreno** [comment]
Fix?

**Comment by auyx** [comment]
I misread the instructions and moved EvilCrow-Keylogger into keylogger-pio. I shouldn't play with this stuff at 2am.
