### ISSUE TITLE
Any idea whare to buy it ?

### ISSUE THREAD

**Issue by AiR-0nE** [joelsernamoreno/EvilCrow-Keylogger#15]
Hello @joelsernamoreno , 
i discover this project, and would like to try it, but i did not find any resseler with stock ? 
Do you have any idea where / how can i get one ? 

Also did you plan to make available schematic and maybe gerber files ? 

Thank you

**Comment by RicardoX2X** [comment]
[Aliexpress Shop](https://www.aliexpress.com/item/4001219974113.html)
[Tindie Shop](https://www.tindie.com/products/aprbrother/evilcrow-keylogger/)
