### ISSUE TITLE
help to install the firmware

### ISSUE THREAD

**Issue by david26099** [joelsernamoreno/EvilCrow-Keylogger#21]
Hello, i just bought my evil crow keylogger and i was been trying to program he but, the auto instalation is not working for 32u4 just for esp32, and i try to program by the ATMEGA32U4.ino file and works, but the wifi is not apering, i put the jumper on right pins, please help

**Comment by joelsernamoreno** [comment]
Hello!

Sorry for replying now, I've been busy the last few weeks

Let me know if you have any other questions

Thanks
