### ISSUE TITLE
Does it need external keyboard?

### ISSUE THREAD

**Issue by Hermenegildogildo** [joelsernamoreno/EvilCrow-Keylogger#6]
question: does this keylogger.need.to be installed between the keyboard and the computer (like with an external keyboard)?
if I plug it to a laptop, will it work when using the laptop.keyboard itself?

**Comment by joelsernamoreno** [comment]
> question: does this keylogger.need.to be installed between the keyboard and the computer (like with an external keyboard)?
> if I plug it to a laptop, will it work when using the laptop.keyboard itself?

Hello!

You need to connect this between an external keyboard and the computer/laptop
