### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by rocolobo** [joelsernamoreno/EvilCrow-Keylogger#7]
Hi Joel,

I bought the Keylogger device. I have a virtual machine with VirtualVox and Ubuntu. I'm a very newbie ... I'm following your instructions, but at this point I get lost:

"Set up a new layout:

0.- Open Keyboard/src/Keyboard.cpp with a text editor"

Where is that path? Should the keylogger device be connected to the PC and the keyboard in this step?

Bests regards

**Comment by rocolobo** [comment]
![image](https://user-images.githubusercontent.com/75254741/100610468-1208ec00-3310-11eb-96d6-9ccd270cb72c.png)

**Comment by joelsernamoreno** [comment]
Hi!

You have to download the Evil Crow Keylogger repository in your Ubuntu VM

Inside this directory you can find the file keyboard.cpp

**Comment by joelsernamoreno** [comment]
If you don't get this, I can connect to your computer with teamviewer and fix this

**Comment by joelsernamoreno** [comment]
If you need this, write me a private message on twitter (@JoelSernaMoreno)

Thanks!

**Comment by rocolobo** [comment]
Thanks Joel¡¡¡How fast¡¡¡

Would it be ok like this?:

![image](https://user-images.githubusercontent.com/75254741/100615831-7465ea80-3318-11eb-982b-a4ea0837ae5b.png)

Sorry, but I don't have social networks ... Is there any way to contact you by email?

Bests Regards

**Comment by rocolobo** [comment]
![image](https://user-images.githubusercontent.com/75254741/100616710-c5c2a980-3319-11eb-947e-6538236791bc.png)

**Comment by rocolobo** [comment]
Which one of the three ways of installation do you recommend?

**Comment by rocolobo** [comment]
I have followed the steps of the first method (Automatic installation), but it gives the following error:

![image](https://user-images.githubusercontent.com/75254741/100628460-8485c600-3328-11eb-8872-e3445812496b.png)

I have edited the file and I have changed pio to pio3, which is the command I had used to do this:

sudo pip3 install pyserial

but the same error comes out...

I think everything is well installed:

![image](https://user-images.githubusercontent.com/75254741/100628942-0a097600-3329-11eb-802f-ec250251d662.png)

**Comment by rocolobo** [comment]
In order to use the pio command, I have done the following:

sudo apt install platformio

But when executing the file ./flash.sh it shows me the following error:

![image](https://user-images.githubusercontent.com/75254741/100634766-fb728d00-332f-11eb-9694-2031a1ae32e0.png)

**Comment by joelsernamoreno** [comment]
Hello!

Do you have telegram? You can contact me by telegram (@JoelSerna)

**Comment by joelsernamoreno** [comment]
Btw... do you have the Evil Crow Keylogger repository in the same directory as keylogger-pio?

**Comment by rocolobo** [comment]
Hi,

No, I do not have. I'm sorry... I only have WhatsApp and email

I have the two folders inside my user (lardin). It is so, right?

**Comment by rocolobo** [comment]
Do I have to install pip for Python3 or for Pyton2?

**Comment by joelsernamoreno** [comment]
I think this is not necessary

Well, send an email here:

joelsernamoreno@gmail.com

**Comment by rocolobo** [comment]
I was missing adding pio to environment variables. Now it has been executed, but it has given errors. I'm sorry... I attach the file:

[Resultado.txt](https://github.com/joelsernamoreno/EvilCrow-Keylogger/files/5617711/Resultado.txt)

**Comment by joelsernamoreno** [comment]
Write me to my email to fix this
